const ExcelJS = require('exceljs');

/**
 * Build an Excel workbook buffer from a report document
 * @param {Object} report - Mongoose report doc
 * @returns {Buffer}
 */
const buildReportExcel = async (report) => {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'Madhura Sales App';
  workbook.created = new Date();

  // ── Sheet 1: Summary ────────────────────────────────────
  const summarySheet = workbook.addWorksheet('Summary');

  const headerStyle = {
    font: { bold: true, color: { argb: 'FFFFFFFF' }, size: 12 },
    fill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF0284C7' } },
    alignment: { vertical: 'middle', horizontal: 'center' },
    border: { bottom: { style: 'thin', color: { argb: 'FFE2E8F0' } } },
  };

  const labelStyle = {
    font: { bold: true, color: { argb: 'FF0F172A' } },
    fill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFEFF6FF' } },
  };

  summarySheet.columns = [
    { key: 'label', width: 30 },
    { key: 'value', width: 30 },
  ];

  summarySheet.addRow(['REPORT SUMMARY', '']).eachCell(cell => Object.assign(cell, headerStyle));
  summarySheet.mergeCells('A1:B1');
  summarySheet.addRow(['Report Title', report.title]).getCell(1).style = labelStyle;
  summarySheet.addRow(['Report Type', report.type]).getCell(1).style = labelStyle;
  summarySheet.addRow(['Period', `${new Date(report.startDate).toLocaleDateString('en-IN')} – ${new Date(report.endDate).toLocaleDateString('en-IN')}`]).getCell(1).style = labelStyle;
  summarySheet.addRow(['Generated By', report.generatedBy?.name || 'System']).getCell(1).style = labelStyle;
  summarySheet.addRow(['Generated On', new Date(report.createdAt).toLocaleString('en-IN')]).getCell(1).style = labelStyle;
  summarySheet.addRow([]);
  summarySheet.addRow(['STATISTICS', '']).eachCell(cell => Object.assign(cell, headerStyle));
  summarySheet.mergeCells('A8:B8');
  summarySheet.addRow(['Total Meetings', report.summary?.totalMeetings || 0]).getCell(1).style = labelStyle;
  summarySheet.addRow(['Total Follow-Ups', report.summary?.totalFollowUps || 0]).getCell(1).style = labelStyle;
  summarySheet.addRow(['Total Tasks', report.summary?.totalTasks || 0]).getCell(1).style = labelStyle;
  summarySheet.addRow(['Completed Tasks', report.summary?.completedTasks || 0]).getCell(1).style = labelStyle;
  summarySheet.addRow(['Active Executives', report.summary?.totalExecutivesActive || 0]).getCell(1).style = labelStyle;

  // ── Sheet 2: Activity Details ────────────────────────────
  const actSheet = workbook.addWorksheet('Activity Details');
  actSheet.columns = [
    { header: 'Date', key: 'date', width: 18 },
    { header: 'Type', key: 'type', width: 14 },
    { header: 'Executive', key: 'executive', width: 22 },
    { header: 'Client Name', key: 'clientName', width: 26 },
    { header: 'Company', key: 'company', width: 26 },
    { header: 'Status / Purpose', key: 'status', width: 22 },
    { header: 'Notes', key: 'notes', width: 40 },
  ];

  actSheet.getRow(1).eachCell(cell => Object.assign(cell, headerStyle));

  (report.activities || []).forEach((act, i) => {
    const row = actSheet.addRow({
      date: act.date ? new Date(act.date).toLocaleDateString('en-IN') : '—',
      type: act.activityType,
      executive: act.executiveName || '—',
      clientName: act.clientName || '—',
      company: act.companyName || '—',
      status: act.status || '—',
      notes: act.notes || '—',
    });
    if (i % 2 === 0) {
      row.eachCell(cell => {
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF8FAFC' } };
      });
    }
  });

  actSheet.autoFilter = { from: 'A1', to: 'G1' };

  const buffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(buffer);
};

module.exports = { buildReportExcel };
