const ExcelJS = require('exceljs');
const CrmQuotation = require('../models/CrmQuotation');
const ProformaInvoice = require('../models/ProformaInvoice');
const TaxInvoice = require('../models/TaxInvoice');
const PaymentReceipt = require('../models/PaymentReceipt');

/**
 * Build an Excel workbook buffer from a report document
 * @param {Object} report - Mongoose report doc
 * @returns {Buffer}
 */
const buildReportExcel = async (report) => {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'Madhura CRM App';
  workbook.created = new Date();

  // ── Sheet 1: Summary ────────────────────────────────────
  const summarySheet = workbook.addWorksheet('Summary');

  const headerStyle = {
    font: { bold: true, color: { argb: 'FFFFFFFF' }, size: 12 },
    fill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF0284C7' } },
    alignment: { vertical: 'middle', horizontal: 'center' },
    border: { bottom: { style: 'thin', color: { argb: 'FFE2E8F0' } } },
  };

  const labelStyle = {
    font: { bold: true, color: { argb: 'FF0F172A' } },
    fill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFEFF6FF' } },
  };

  summarySheet.columns = [
    { key: 'label', width: 30 },
    { key: 'value', width: 30 },
  ];

  summarySheet.addRow(['REPORT SUMMARY', '']).eachCell(cell => Object.assign(cell, headerStyle));
  summarySheet.mergeCells('A1:B1');
  summarySheet.addRow(['Report Title', report.title]).getCell(1).style = labelStyle;
  summarySheet.addRow(['Report Type', report.type]).getCell(1).style = labelStyle;
  summarySheet.addRow(['Period', `${new Date(report.startDate).toLocaleDateString('en-IN')} – ${new Date(report.endDate).toLocaleDateString('en-IN')}`]).getCell(1).style = labelStyle;
  summarySheet.addRow(['Generated By', report.generatedBy?.name || 'System']).getCell(1).style = labelStyle;
  summarySheet.addRow(['Generated On', new Date(report.createdAt).toLocaleString('en-IN')]).getCell(1).style = labelStyle;
  summarySheet.addRow([]);
  summarySheet.addRow(['STATISTICS', '']).eachCell(cell => Object.assign(cell, headerStyle));
  summarySheet.mergeCells('A8:B8');
  summarySheet.addRow(['Total Meetings', report.summary?.totalMeetings || 0]).getCell(1).style = labelStyle;
  summarySheet.addRow(['Total Follow-Ups', report.summary?.totalFollowUps || 0]).getCell(1).style = labelStyle;
  summarySheet.addRow(['Total Tasks', report.summary?.totalTasks || 0]).getCell(1).style = labelStyle;
  summarySheet.addRow(['Completed Tasks', report.summary?.completedTasks || 0]).getCell(1).style = labelStyle;
  summarySheet.addRow(['Active Executives', report.summary?.totalExecutivesActive || 0]).getCell(1).style = labelStyle;

  if (report.customClientName || report.customProjectName || report.customSummary) {
    summarySheet.addRow([]);
    summarySheet.addRow(['CUSTOM REPORT DETAILS', '']).eachCell(cell => Object.assign(cell, headerStyle));
    summarySheet.mergeCells(`A${summarySheet.rowCount}:B${summarySheet.rowCount}`);
    
    if (report.customClientName) {
      summarySheet.addRow(['Client Name', report.customClientName]).getCell(1).style = labelStyle;
      summarySheet.getRow(summarySheet.rowCount).getCell(2).alignment = { wrapText: true, vertical: 'top' };
    }
    if (report.customProjectName) {
      summarySheet.addRow(['Project / Subject', report.customProjectName]).getCell(1).style = labelStyle;
      summarySheet.getRow(summarySheet.rowCount).getCell(2).alignment = { wrapText: true, vertical: 'top' };
    }
    if (report.customSummary) {
      summarySheet.addRow(['Executive Summary', report.customSummary]).getCell(1).style = labelStyle;
      summarySheet.getRow(summarySheet.rowCount).getCell(2).alignment = { wrapText: true, vertical: 'top' };
    }
    if (report.customNextSteps) {
      summarySheet.addRow(['Next Steps', report.customNextSteps]).getCell(1).style = labelStyle;
      summarySheet.getRow(summarySheet.rowCount).getCell(2).alignment = { wrapText: true, vertical: 'top' };
    }
    if (report.customQuotes) {
      summarySheet.addRow(['Quotations / Pricing', report.customQuotes]).getCell(1).style = labelStyle;
      summarySheet.getRow(summarySheet.rowCount).getCell(2).alignment = { wrapText: true, vertical: 'top' };
    }
  }

  // ── Sheet 2: Activity Details ────────────────────────────
  const actSheet = workbook.addWorksheet('Activity Details');
  actSheet.columns = [
    { header: 'Date', key: 'date', width: 18 },
    { header: 'Type', key: 'type', width: 14 },
    { header: 'Executive', key: 'executive', width: 22 },
    { header: 'Client Name', key: 'clientName', width: 26 },
    { header: 'Company', key: 'company', width: 26 },
    { header: 'Status / Purpose', key: 'status', width: 22 },
    { header: 'Notes', key: 'notes', width: 40 },
  ];

  actSheet.getRow(1).eachCell(cell => Object.assign(cell, headerStyle));

  (report.activities || []).forEach((act, i) => {
    const row = actSheet.addRow({
      date: act.date ? new Date(act.date).toLocaleDateString('en-IN') : '—',
      type: act.activityType,
      executive: act.executiveName || '—',
      clientName: act.clientName || '—',
      company: act.companyName || '—',
      status: act.status || '—',
      notes: act.notes || '—',
    });
    if (i % 2 === 0) {
      row.eachCell(cell => {
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF8FAFC' } };
      });
    }
  });

  actSheet.autoFilter = { from: 'A1', to: 'G1' };

  // ── Sheets for Financial Data ────────────────────────────
  if (report.clientId || report.customClientName) {
    let quotations = [];
    let proformaInvoices = [];
    let taxInvoices = [];
    let paymentReceipts = [];

    try {
      if (report.clientId) {
        quotations = await CrmQuotation.find({ customer_id: report.clientId }).lean();
        proformaInvoices = await ProformaInvoice.find({ customer_id: report.clientId }).lean();
        taxInvoices = await TaxInvoice.find({ client_id: report.clientId }).lean();
      }

      const taxInvoiceIds = taxInvoices.map(inv => inv._id);
      const taxInvoiceNos = taxInvoices.map(inv => inv.invoice_no);
      
      const receiptQuery = {
        $or: [
          { invoice_id: { $in: taxInvoiceIds } },
          { invoice_no: { $in: taxInvoiceNos } }
        ]
      };
      
      if (report.customClientName && report.customClientName.trim() !== '') {
        receiptQuery.$or.push({ client_company: new RegExp(`^${report.customClientName}$`, 'i') });
      }

      if (taxInvoiceIds.length > 0 || (report.customClientName && report.customClientName.trim() !== '')) {
        paymentReceipts = await PaymentReceipt.find(receiptQuery).lean();
      }

      // Add Quotations Sheet
      if (quotations.length > 0) {
        const qSheet = workbook.addWorksheet('Quotations');
        qSheet.columns = [
          { header: 'Date', key: 'date', width: 15 },
          { header: 'Reference No', key: 'ref', width: 20 },
          { header: 'Grand Total', key: 'total', width: 15 }
        ];
        qSheet.getRow(1).eachCell(cell => Object.assign(cell, headerStyle));
        quotations.forEach(q => {
          qSheet.addRow({
            date: new Date(q.quotation_date).toLocaleDateString('en-IN'),
            ref: q.reference_no || q._id.toString().slice(-6),
            total: q.grand_total
          });
        });
      }

      // Add Proforma Invoices Sheet
      if (proformaInvoices.length > 0) {
        const pSheet = workbook.addWorksheet('Proforma Invoices');
        pSheet.columns = [
          { header: 'Date', key: 'date', width: 15 },
          { header: 'Reference No', key: 'ref', width: 20 },
          { header: 'Grand Total', key: 'total', width: 15 }
        ];
        pSheet.getRow(1).eachCell(cell => Object.assign(cell, headerStyle));
        proformaInvoices.forEach(p => {
          pSheet.addRow({
            date: new Date(p.invoice_date).toLocaleDateString('en-IN'),
            ref: p.reference_no || p.invoice_no || p._id.toString().slice(-6),
            total: p.grand_total
          });
        });
      }

      // Add Tax Invoices Sheet
      if (taxInvoices.length > 0) {
        const tSheet = workbook.addWorksheet('Tax Invoices');
        tSheet.columns = [
          { header: 'Bill Date', key: 'date', width: 15 },
          { header: 'Invoice No', key: 'invNo', width: 20 },
          { header: 'Service No', key: 'srvNo', width: 20 },
          { header: 'Advance', key: 'adv', width: 15 },
        ];
        tSheet.getRow(1).eachCell(cell => Object.assign(cell, headerStyle));
        taxInvoices.forEach(t => {
          tSheet.addRow({
            date: new Date(t.bill_date).toLocaleDateString('en-IN'),
            invNo: t.invoice_no,
            srvNo: t.service_no,
            adv: t.advance_amount
          });
        });
      }

      // Add Payment Receipts Sheet
      if (paymentReceipts.length > 0) {
        const rSheet = workbook.addWorksheet('Payment Receipts');
        rSheet.columns = [
          { header: 'Date', key: 'date', width: 15 },
          { header: 'Receipt No', key: 'recNo', width: 20 },
          { header: 'Invoice No', key: 'invNo', width: 20 },
          { header: 'Method', key: 'method', width: 15 },
          { header: 'Total Received', key: 'total', width: 18 },
        ];
        rSheet.getRow(1).eachCell(cell => Object.assign(cell, headerStyle));
        paymentReceipts.forEach(r => {
          rSheet.addRow({
            date: new Date(r.receipt_date).toLocaleDateString('en-IN'),
            recNo: r.receipt_no,
            invNo: r.invoice_no,
            method: r.payment_method,
            total: r.total_amount
          });
        });
      }
    } catch (err) {
      console.error("Error fetching financial documents for Excel:", err);
    }
  }

  const buffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(buffer);
};

module.exports = { buildReportExcel };
